"""Phase 10 — render every results table/macro in the paper from committed JSONs.

Single source of truth for paper numbers:
  results/phase8_reanalysis/reanalysis.json   (exploratory, historical val)
  results/phase9_rerun/rerun_analysis.json    (confirmatory, untouched test)
  results/phase4/*.json                       (per-run values for means)

Emits LaTeX fragments into tables/*.tex which paper.tex \\input{}s, plus
tables/macros.tex with inline-number macros. Rerun after any analysis change;
never hand-edit the fragments. An independent reader reproduces the paper's
principal tables by running:
    uv run python scripts/p8_dependence_reanalysis.py   (needs stream index)
    uv run python scripts/p9_analyze_rerun.py           (needs rerun JSONs)
    uv run python scripts/p10_render_paper_tables.py
"""

from __future__ import annotations

import glob
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
P4 = ROOT / "results" / "phase4"
P8 = ROOT / "results" / "phase8_reanalysis" / "reanalysis.json"
P9 = ROOT / "results" / "phase9_rerun" / "rerun_analysis.json"
TABDIR = ROOT / "tables"

MACROS: dict[str, str] = {}

_CLS_HIST = {"tap": "click", "type": "type", "swipe_up": "scroll",
             "swipe_down": "scroll", "swipe_left": "scroll", "swipe_right": "scroll"}


def macro(name: str, value: str) -> None:
    assert name.isalpha(), f"macro names must be alphabetic: {name}"
    MACROS[name] = value


def fmt_p(r: dict) -> str:
    """Table cell: math-mode p-value, floored at Monte Carlo resolution."""
    p, res = r["p_value"], r["p_resolution"]
    return f"$<10^{{{_mag(res)}}}$" if p <= res else f"${p:.3g}$"


def _mag(x: float) -> int:
    """Ceiling power of ten, e.g. 9.999e-05 -> -4."""
    import math
    return int(math.ceil(math.log10(x)))


def p_inline(r: dict) -> str:
    """Inline macro body for use inside an existing `$p=...$`: no delimiters,
    and never claims more precision than the permutation budget supports."""
    p, res = r["p_value"], r["p_resolution"]
    return f"{p:.3g}" if p > res else f"{{<}}10^{{{_mag(res)}}}"


def ci(r: dict, digits: int = 3) -> str:
    d = f"{{:+.{digits}f}}"
    return (f"${d.format(r['delta'])}$ "
            f"[{d.format(r['ci_low'])}, {d.format(r['ci_high'])}]")


def _metric_from_ped(ped: list[float], key: str) -> float:
    """Metric from per-example distances with parse failures ALREADY scored at
    the sqrt(2) sentinel — the paper's declared convention (misses counted).
    The run JSONs' headline hit/L2 fields use a parsed-only denominator and
    must never feed paper tables (audit finding: C's parse_rate < 1 made its
    raw headline numbers inconsistent with the reanalysis + delta columns)."""
    a = np.asarray(ped, dtype=np.float64)
    if key == "mean_normalized_l2":
        return float(a.mean())
    r = {"hit_at_005": 0.05, "hit_at_010": 0.10, "hit_at_025": 0.25}[key]
    return float((a <= r).mean())


def seed_stats(files: list[str], which: str, key: str) -> tuple[float, float, list[float]]:
    vals = []
    for f in files:
        d = json.loads(Path(f).read_text())
        m = d["final_test_metrics"] if which == "test" else d["final_val_metrics"]
        vals.append(m[key] if key == "parse_rate" else _metric_from_ped(m["per_example_dist"], key))
    a = np.asarray(vals, dtype=np.float64)
    return float(a.mean()), float(a.std(ddof=1)), [float(v) for v in a]


def hist_stats(pattern: str, key: str) -> tuple[float, float]:
    vals = []
    for f in sorted(glob.glob(str(P4 / pattern))):
        d = json.loads(Path(f).read_text())
        vals.append(_metric_from_ped(d["final_val_metrics"]["per_example_dist"], key))
    a = np.asarray(vals, dtype=np.float64)
    return float(a.mean()), float(a.std(ddof=1))


def write(name: str, lines: list[str]) -> None:
    TABDIR.mkdir(exist_ok=True)
    (TABDIR / name).write_text("% AUTO-GENERATED by scripts/p10_render_paper_tables.py — do not edit\n"
                               + "\n".join(lines) + "\n")
    print(f"[p10] wrote tables/{name}")


def exploratory(p8: dict) -> None:
    cell = p8["cells"]["awc_n1200"]

    # ---- leakage table ----
    lk = p8["leakage"]
    L = [r"\begin{tabular}{lccc}", r"\toprule",
         r"historical cell & val steps & sharing a train episode & sharing a train goal \\",
         r"\midrule"]
    order = ["awc_n300", "awc_n500", "awc_n800", "awc_n1200", "awc_n2500", "awc_n5000", "ts_n1000"]
    names = {"awc_n300": r"all\_wc, $n{=}300$", "awc_n500": r"all\_wc, $n{=}500$",
             "awc_n800": r"all\_wc, $n{=}800$", "awc_n1200": r"all\_wc, $n{=}1200$",
             "awc_n2500": r"all\_wc, $n{=}2500$", "awc_n5000": r"all\_wc, $n{=}5000$",
             "ts_n1000": r"taps\_swipes, $n{=}1000$"}
    for k in order:
        v = lk[k]
        L.append(f"{names[k]} & {v['n_val']} & "
                 f"{v['val_steps_sharing_train_episode']} ({100*v['val_steps_sharing_train_episode_frac']:.0f}\\%) & "
                 f"{v['val_steps_sharing_train_goal']} ({100*v['val_steps_sharing_train_goal_frac']:.0f}\\%) \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("tab_leakage.tex", L)
    macro("LeakGoalMain", f"{100*lk['awc_n1200']['val_steps_sharing_train_goal_frac']:.0f}\\%")
    macro("LeakGoalMax", f"{100*lk['awc_n5000']['val_steps_sharing_train_goal_frac']:.0f}\\%")
    macro("LeakEpMain", f"{100*lk['awc_n1200']['val_steps_sharing_train_episode_frac']:.0f}\\%")

    # ---- exploratory main ablation ----
    pats = {
        "A (flat)": "variantA_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords.json",
        "B (aux loss)": "variantB_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords_aux1.0.json",
        "C (hard routing)": "variantC_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords.json",
        "D-hook (additive)": "Dhook_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords_init0.0.json",
        "D-token (prepended)": "Dtoken_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords_init0.02.json",
    }
    ckey = {"B (aux loss)": "B_vs_A", "C (hard routing)": "C_vs_A",
            "D-hook (additive)": "Dhook_vs_A", "D-token (prepended)": "Dtoken_vs_A"}
    L = [r"\begin{tabular}{lcccc}", r"\toprule",
         r"variant & hit@0.10 & L2 $\downarrow$ & $\Delta$ vs.\ A [95\% CI] & $p$ \\",
         r"\midrule"]
    for nm, pat in pats.items():
        m10, s10 = hist_stats(pat, "hit_at_010")
        l2, _ = hist_stats(pat, "mean_normalized_l2")
        if nm in ckey:
            r = cell[ckey[nm]]["metrics"]["hit_at_010"]["episode_clustered"]
            L.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & {ci(r)} & {fmt_p(r)} \\\\")
        else:
            L.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & --- & --- \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("tab_exploratory_main.tex", L)

    rB = cell["B_vs_A"]["metrics"]["hit_at_010"]["episode_clustered"]
    macro("ExpBvsA", ci(rB))
    macro("ExpBvsAp", p_inline(rB))
    macro("ExpBvsAHolm", f"{cell['B_vs_A']['metrics']['hit_at_010']['holm_adjusted_p_vsA_family']:.3f}")
    rD = cell["Dhook_vs_A"]["metrics"]["hit_at_010"]["episode_clustered"]
    macro("ExpDhvsA", ci(rD))
    macro("ExpDhvsAp", p_inline(rD))
    macro("ExpDhvsAHolm", f"{cell['Dhook_vs_A']['metrics']['hit_at_010']['holm_adjusted_p_vsA_family']:.3f}")
    rDtB = cell["Dtoken_vs_B"]["metrics"]["hit_at_010"]["episode_clustered"]
    macro("ExpDtvsB", ci(rDtB))
    macro("ExpDtvsBp", p_inline(rDtB))
    legacy = cell["B_vs_A"]["metrics"]["hit_at_010"]["legacy_pooled"]
    macro("ExpBvsApooled", f"{legacy['p_value']:.4g}")
    # The pooled p that produced the course-era "D-token is refuted" verdict.
    macro("ExpDtvsBpooled",
          f"{cell['Dtoken_vs_B']['metrics']['hit_at_010']['legacy_pooled']['p_value']:.3g}")

    # ---- exploratory per-class, matched seeds + miss-scored ----
    # The historical runs' own `per_class` block uses parsed-only denominators
    # AND (via scripts/p7_compounding_error.py) a 5-seed A/D-hook baseline
    # against 3-seed B/C/D-token. Both are fixed here: classes come from the
    # reconstructed val slice, seeds are matched to 42-44, and parse failures
    # score the sqrt(2) sentinel like everywhere else.
    scan = sorted((ROOT / "results" / "phase8_reanalysis").glob("stream_index_train_n*.json"))
    if scan:
        recs = json.loads(scan[-1].read_text())["records"]
        AWC = {"tap", "swipe_up", "swipe_down", "swipe_left", "swipe_right", "type"}
        awc = [r for r in recs if r["label"] in AWC]
        val_slice = awc[1200:1450]          # the historical n_train=1200 val slice
        cls = [_CLS_HIST[r["label"]] for r in val_slice]

        def exp_per_class(pat: str) -> dict:
            out: dict[str, list[float]] = {}
            for f in sorted(glob.glob(str(P4 / pat))):
                d = json.loads(Path(f).read_text())
                dist = np.asarray(d["final_val_metrics"]["per_example_dist"], dtype=np.float64)
                if dist.shape[0] != len(cls):
                    continue
                for c in sorted(set(cls)):
                    m = np.array([x == c for x in cls])
                    out.setdefault(c, []).append(float((dist[m] <= 0.10).mean()))
            return {c: float(np.mean(v)) for c, v in out.items()}

        expc = {nm: exp_per_class(pat) for nm, pat in pats.items()}
        base = expc.get("A (flat)", {})
        name_map = {"B (aux loss)": "ExpB", "C (hard routing)": "ExpC",
                    "D-hook (additive)": "ExpDh", "D-token (prepended)": "ExpDt"}
        for nm, pre in name_map.items():
            for c, suf in (("click", "click"), ("scroll", "scroll")):
                if c in base and c in expc.get(nm, {}):
                    macro(pre + suf.capitalize() + "Delta",
                          f"{expc[nm][c] - base[c]:+.3f}")

    # ---- validation numbers ----
    v = p8["validation"]
    macro("TypeIPooled", f"{100*v['fixed_checkpoint_null']['pooled_reject_rate']:.1f}\\%")
    macro("TypeIClustered", f"{100*v['fixed_checkpoint_null']['clustered_reject_rate']:.1f}\\%")
    macro("TypeISims", str(v["fixed_checkpoint_null"]["n_sims"]))
    macro("TypeIProc", f"{100*v['procedure_null_with_run_offsets']['clustered_reject_rate']:.0f}\\%")

    # ---- exploratory causal table ----
    if "dtoken_causal_n1200" in p8["cells"]:
        cc = p8["cells"]["dtoken_causal_n1200"]
        L = [r"\begin{tabular}{lccc}", r"\toprule",
             r"contrast & $\Delta$ hit@0.10 [95\% CI] & $\Delta$ hit@0.25 [95\% CI] & $p$ \\",
             r"\midrule"]
        for key, label in [("wrong_vs_gold", "wrong $-$ gold"), ("zero_vs_gold", "zero $-$ gold")]:
            r10 = cc[key]["metrics"]["hit_at_010"]["episode_clustered"]
            r25 = cc[key]["metrics"]["hit_at_025"]["episode_clustered"]
            L.append(f"{label} & {ci(r10)} & {ci(r25)} & {fmt_p(r10)} \\\\")
        L += [r"\bottomrule", r"\end{tabular}"]
        write("tab_causal.tex", L)

    # ---- exploratory e2e ----
    if "e2e_n1200" in p8["cells"]:
        ee = p8["cells"]["e2e_n1200"]
        rp = ee["predicted_vs_flatA"]["metrics"]["hit_at_010"]["episode_clustered"]
        ro = ee["oracle_vs_flatA"]["metrics"]["hit_at_010"]["episode_clustered"]
        rg = ee["predicted_vs_oracle"]["metrics"]["hit_at_010"]["episode_clustered"]
        macro("ExpEtoEPredvsA", ci(rp)); macro("ExpEtoEPredvsAp", p_inline(rp))
        macro("ExpEtoEOraclevsA", ci(ro))
        macro("ExpEtoEGap", ci(rg))


def confirmatory(p9: dict) -> None:
    fs = "_fs-aitw_frozen_v1"

    # ---- descriptive test means ----
    pats = {
        "A (flat)": f"variantA_seed4[234]_n1200_*mix-all_with_coords{fs}.json",
        "B (aux loss)": f"variantB_seed4[234]_n1200_*aux1.0{fs}.json",
        "C (hard routing)": f"variantC_seed4[234]_n1200_*mix-all_with_coords{fs}.json",
        "D-hook (additive)": f"Dhook_seed4[234]_n1200_*init0.0{fs}.json",
        "D-token (prepended)": f"Dtoken_seed4[234]_n1200_*init0.02_causal{fs}.json",
    }
    stats = {}
    for nm, pat in pats.items():
        files = sorted(glob.glob(str(P4 / pat)))
        if len(files) != 3:
            print(f"[p10] WARNING: {nm}: {len(files)} test runs found (expected 3)")
        if files:
            stats[nm] = {
                "hit010": seed_stats(files, "test", "hit_at_010"),
                "hit025": seed_stats(files, "test", "hit_at_025"),
                "l2": seed_stats(files, "test", "mean_normalized_l2"),
                "parse": seed_stats(files, "test", "parse_rate"),
            }
    pri = p9["primary"]
    cmap = {"B (aux loss)": ("P1_B_vs_A", False), "D-hook (additive)": ("P2_Dhook_vs_A", False),
            "C (hard routing)": ("C_vs_A", True), "D-token (prepended)": ("Dtoken_vs_A", True)}
    L = [r"\begin{tabular}{lccccc}", r"\toprule",
         r"variant & hit@0.10 & L2 $\downarrow$ & parse & $\Delta$ vs.\ A [95\% CI] & $p$ (Holm) \\",
         r"\midrule"]
    for nm in pats:
        if nm not in stats:
            continue
        m10, s10, _ = stats[nm]["hit010"]
        l2, _, _ = stats[nm]["l2"]
        pr, _, _ = stats[nm]["parse"]
        prs = f"${100*pr:.1f}\\%$"
        if nm in cmap:
            key, secondary = cmap[nm]
            src = p9["secondary"] if secondary else p9["primary"]
            r = src[key]["metrics"]["hit_at_010"]["episode_clustered"]
            hp = src[key].get("holm_adjusted_p_hit010")
            censored = r["p_value"] <= r["p_resolution"]
            holm = "" if secondary else (
                f" ($\\leq${hp:.2g})" if censored else f" ({hp:.3g})")
            L.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & {prs} & {ci(r)} & {fmt_p(r)}{holm} \\\\")
        else:
            L.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & {prs} & --- & --- \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("tab_confirmatory_main.tex", L)

    for mk, key in [("ConfBvsA", "P1_B_vs_A"), ("ConfDhvsA", "P2_Dhook_vs_A"),
                    ("ConfDtvsB", "P3_Dtoken_vs_B"), ("ConfEtoEvsA", "P4_e2e_pred_vs_A")]:
        r = pri[key]["metrics"]["hit_at_010"]["episode_clustered"]
        macro(mk, ci(r))
        macro(mk + "p", p_inline(r))
        _hp = pri[key]["holm_adjusted_p_hit010"]
        macro(mk + "Holm", (f"{{\\leq}}{_hp:.2g}"
                            if r["p_value"] <= r["p_resolution"] else f"{_hp:.3g}"))
        rl = pri[key]["metrics"]["mean_normalized_l2"]["episode_clustered"]
        macro(mk + "Ltwo", ci(rl))
        macro(mk + "Ltwop", p_inline(rl))

    if "A (flat)" in stats:
        m10, s10, seeds = stats["A (flat)"]["hit010"]
        macro("ConfAhit", f"{m10:.3f} \\pm {s10:.3f}")
        pr, _, _ = stats["A (flat)"]["parse"]
        macro("ConfAparse", f"{100*pr:.1f}\\%")
    if "B (aux loss)" in stats:
        m10, s10, _ = stats["B (aux loss)"]["hit010"]
        macro("ConfBhit", f"{m10:.3f} \\pm {s10:.3f}")

    # ---- control ----
    rows = []
    for nm, pat, key in [
        ("A (flat)", f"variantA_seed4[234]_n1000_*mix-taps_and_swipes{fs}.json", None),
        ("B (aux loss)", f"variantB_seed4[234]_n1000_*taps_and_swipes_aux1.0{fs}.json", "control_B_vs_A"),
        ("C (hard routing)", f"variantC_seed4[234]_n1000_*mix-taps_and_swipes{fs}.json", "control_C_vs_A"),
        ("D-hook (additive)", f"Dhook_seed4[234]_n1000_*taps_and_swipes_init0.0{fs}.json", "control_Dhook_vs_A"),
    ]:
        files = sorted(glob.glob(str(P4 / pat)))
        if not files:
            continue
        m10, s10, _ = seed_stats(files, "test", "hit_at_010")
        l2, _, _ = seed_stats(files, "test", "mean_normalized_l2")
        pr, _, _ = seed_stats(files, "test", "parse_rate")
        prs = f"${100*pr:.1f}\\%$"
        if key and key in p9["secondary"]:
            r = p9["secondary"][key]["metrics"]["hit_at_010"]["episode_clustered"]
            rows.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & {prs} & {ci(r)} & {fmt_p(r)} \\\\")
        else:
            rows.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & {prs} & --- & --- \\\\")
    if rows:
        L = [r"\begin{tabular}{lccccc}", r"\toprule",
             r"variant & hit@0.10 & L2 $\downarrow$ & parse & $\Delta$ vs.\ A [95\% CI] & $p$ \\",
             r"\midrule"] + rows + [r"\bottomrule", r"\end{tabular}"]
        write("tab_control.tex", L)

    # ---- low-data grid ----
    rows = []
    for n in (300, 500, 800):
        cols = [f"$n{{=}}{n}$"]
        fa = sorted(glob.glob(str(P4 / f"variantA_seed4[234]_n{n}_*mix-all_with_coords{fs}.json")))
        if not fa:
            continue
        ma, _, _ = seed_stats(fa, "test", "hit_at_010")
        cols.append(f"${ma:.3f}$")
        for vk, ck in [("variantB", f"lowdata{n}_B_vs_A"), ("Dhook", f"lowdata{n}_Dhook_vs_A")]:
            if ck in p9["secondary"]:
                r = p9["secondary"][ck]["metrics"]["hit_at_010"]["episode_clustered"]
                cols.append(ci(r))
            else:
                cols.append("---")
        rows.append(" & ".join(cols) + r" \\")
    if rows:
        L = [r"\begin{tabular}{lccc}", r"\toprule",
             r"$n_{\text{train}}$ & A & $\Delta$ B$-$A [95\% CI] & $\Delta$ D-hook$-$A [95\% CI] \\",
             r"\midrule"] + rows + [r"\bottomrule", r"\end{tabular}"]
        write("tab_lowdata.tex", L)

    # ---- confirmatory per-class decomposition (seed-averaged, test) ----
    # AITW string label -> canonical class used in the paper's per-class table.
    _CLS = {"tap": "click", "type": "type", "swipe_up": "scroll",
            "swipe_down": "scroll", "swipe_left": "scroll", "swipe_right": "scroll"}

    def per_class_means(pat: str) -> dict:
        """Per-class hit@0.10 computed from per_example_dist grouped by the
        frozen split's own step labels, so parse failures are sentinel-scored
        and counted as misses — the paper's declared convention. The run
        JSONs' `per_class` block uses parsed-only denominators (audit finding:
        C's 3.8% test parse failures inflated its per-class scroll rate), so
        it must not feed paper tables."""
        acc: dict[str, list[float]] = {}
        ns: dict[str, int] = {}
        for f in sorted(glob.glob(str(P4 / pat))):
            d = json.loads(Path(f).read_text())
            dist = np.asarray(d["final_test_metrics"]["per_example_dist"], dtype=np.float64)
            labels = [_CLS[k["label"]] for k in d["test_step_keys"]]
            assert len(labels) == dist.shape[0], f"{f}: keys/dist length mismatch"
            for cls in sorted(set(labels)):
                mask = np.array([l == cls for l in labels])
                acc.setdefault(cls, []).append(float((dist[mask] <= 0.10).mean()))
                ns[cls] = int(mask.sum())
        return {c: (float(np.mean(vs)), ns[c]) for c, vs in acc.items()}

    pc_rows = {nm: per_class_means(pat) for nm, pat in pats.items()}
    if pc_rows.get("A (flat)"):
        classes = [c for c in ("click", "scroll", "type") if c in pc_rows["A (flat)"]]
        head = " & ".join(f"{c} ($n{{=}}{pc_rows['A (flat)'][c][1]}$)" for c in classes)
        L = [r"\begin{tabular}{l" + "c" * len(classes) + "}", r"\toprule",
             f"variant & {head} \\\\", r"\midrule"]
        for nm in pats:
            if nm not in pc_rows or not pc_rows[nm]:
                continue
            cells = []
            for c in classes:
                v = pc_rows[nm].get(c)
                cells.append(f"${v[0]:.3f}$" if v else "---")
            L.append(f"{nm} & " + " & ".join(cells) + r" \\")
        L += [r"\bottomrule", r"\end{tabular}"]
        write("tab_confirmatory_perclass.tex", L)
        a_pc, dh_pc = pc_rows["A (flat)"], pc_rows.get("D-hook (additive)", {})
        if "scroll" in a_pc and "scroll" in dh_pc:
            macro("ConfAscroll", f"{a_pc['scroll'][0]:.3f}")
            macro("ConfDhscroll", f"{dh_pc['scroll'][0]:.3f}")
            macro("ConfScrollDelta", f"{dh_pc['scroll'][0] - a_pc['scroll'][0]:+.3f}")
        if "click" in a_pc and "click" in dh_pc:
            macro("ConfAclick", f"{a_pc['click'][0]:.3f}")
            macro("ConfDhclick", f"{dh_pc['click'][0]:.3f}")
            macro("ConfClickDelta", f"{dh_pc['click'][0] - a_pc['click'][0]:+.3f}")
        # Absolute share of the aggregate gain each class supplies. The
        # proportional (fold) effect is largest on scroll, but click is 3x
        # more frequent, so click still supplies most of the absolute gain —
        # the text must not claim the gain "concentrates in scroll".
        if a_pc.get("click") and a_pc.get("scroll") and dh_pc:
            c_abs = a_pc["click"][1] * (dh_pc["click"][0] - a_pc["click"][0])
            s_abs = a_pc["scroll"][1] * (dh_pc["scroll"][0] - a_pc["scroll"][0])
            macro("ConfClickAbsShare", f"{100 * c_abs / (c_abs + s_abs):.0f}\\%")
            macro("ConfScrollAbsShare", f"{100 * s_abs / (c_abs + s_abs):.0f}\\%")
        # Relative (fold) improvements, so the text never hand-types a ratio.
        if a_pc.get("scroll", (0,))[0]:
            macro("ConfScrollFold", f"{dh_pc['scroll'][0] / a_pc['scroll'][0]:.1f}")
        if a_pc.get("click", (0,))[0]:
            macro("ConfClickFold", f"{dh_pc['click'][0] / a_pc['click'][0]:.1f}")

    # ---- e2e on test ----
    e2f = sorted(glob.glob(str(P4 / f"e2e_seed4[234]_n1200_*mix-all_with_coords{fs}.json")))
    if e2f:
        po, pp, s1a = [], [], []
        for f in e2f:
            d = json.loads(Path(f).read_text())
            tb = d["final_test_metrics"]
            po.append(_metric_from_ped(tb["oracle_metrics"]["per_example_dist"], "hit_at_010"))
            pp.append(_metric_from_ped(tb["predicted_metrics"]["per_example_dist"], "hit_at_010"))
            s1a.append(tb["stage1_test_acc"])
        macro("ConfEtoEOracle", f"{np.mean(po):.3f} \\pm {np.std(po, ddof=1):.3f}")
        macro("ConfEtoEPred", f"{np.mean(pp):.3f} \\pm {np.std(pp, ddof=1):.3f}")
        macro("ConfStageOneAcc", f"{np.mean(s1a):.3f}")
        rg = p9["secondary"]["e2e_pred_vs_oracle"]["metrics"]["hit_at_010"]["episode_clustered"]
        macro("ConfEtoEGap", ci(rg))
        macro("ConfEtoEGapp", p_inline(rg))
        # Share of the e2e oracle arm's advantage over A that Stage-1 error
        # absorbs. Reported descriptively (no new significance test) so the
        # text never overstates the gap relative to the oracle advantage.
        a_hit, _, _ = seed_stats(
            sorted(glob.glob(str(P4 / f"variantA_seed4[234]_n1200_*mix-all_with_coords{fs}.json"))),
            "test", "hit_at_010")
        oracle_adv = float(np.mean(po)) - a_hit
        macro("ConfEtoEOracleAdv", f"{oracle_adv:+.3f}")
        macro("ConfEtoEGapShare", f"{100 * abs(rg['delta']) / oracle_adv:.0f}\\%")
        # Stage-1 accuracy on the frozen val split vs the untouched test split:
        # the generalization drop that explains why the oracle gain does not
        # survive the real classifier.
        s1v = [json.loads(Path(f).read_text())["stage1_val_acc"] for f in e2f]
        macro("ConfStageOneValAcc", f"{np.mean(s1v):.3f}")
    for nm, key in [("ConfCvsA", "C_vs_A"), ("ConfDtvsA", "Dtoken_vs_A"),
                    ("ConfDhvsB", "Dhook_vs_B"),
                    ("ConfCtrlDhvsA", "control_Dhook_vs_A"),
                    ("ConfCtrlBvsA", "control_B_vs_A"),
                    ("ConfCtrlCvsA", "control_C_vs_A")]:
        if key in p9["secondary"]:
            rr = p9["secondary"][key]["metrics"]["hit_at_010"]["episode_clustered"]
            macro(nm, ci(rr))
            macro(nm + "p", p_inline(rr))


def main() -> None:
    TABDIR.mkdir(exist_ok=True)
    p8 = json.loads(P8.read_text())
    exploratory(p8)
    if P9.exists():
        confirmatory(json.loads(P9.read_text()))
    else:
        print("[p10] rerun_analysis.json missing — confirmatory tables NOT rendered")
        for t in ("tab_confirmatory_main.tex", "tab_control.tex", "tab_lowdata.tex"):
            write(t, [r"\begin{tabular}{l}\textbf{PENDING: confirmatory rerun results not yet rendered}\end{tabular}"])
    lines = [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in MACROS.items()]
    write("macros.tex", lines)
    print(f"[p10] {len(MACROS)} macros")


if __name__ == "__main__":
    main()
