"""Phase 10 — render every results table/macro in the paper from committed JSONs.

Single source of truth for paper numbers:
  results/phase8_reanalysis/reanalysis.json   (exploratory, historical val)
  results/phase9_rerun/rerun_analysis.json    (confirmatory, untouched test)
  results/phase4/*.json                       (per-run values for means)

Emits LaTeX fragments into tables/*.tex which paper.tex \\input{}s, plus
tables/macros.tex with inline-number macros. Rerun after any analysis change;
never hand-edit the fragments. An independent reader reproduces the paper's
principal tables by running:
    uv run python scripts/p8_dependence_reanalysis.py   (needs stream index)
    uv run python scripts/p9_analyze_rerun.py           (needs rerun JSONs)
    uv run python scripts/p10_render_paper_tables.py
"""

from __future__ import annotations

import glob
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
P4 = ROOT / "results" / "phase4"
P8 = ROOT / "results" / "phase8_reanalysis" / "reanalysis.json"
P9 = ROOT / "results" / "phase9_rerun" / "rerun_analysis.json"
TABDIR = ROOT / "tables"

MACROS: dict[str, str] = {}


def macro(name: str, value: str) -> None:
    assert name.isalpha(), f"macro names must be alphabetic: {name}"
    MACROS[name] = value


def fmt_p(r: dict) -> str:
    p, res = r["p_value"], r["p_resolution"]
    return f"$\\leq {res:.4g}$" if p <= res else f"${p:.3g}$"


def ci(r: dict, digits: int = 3) -> str:
    d = f"{{:+.{digits}f}}"
    return (f"${d.format(r['delta'])}$ "
            f"[{d.format(r['ci_low'])}, {d.format(r['ci_high'])}]")


def seed_stats(files: list[str], which: str, key: str) -> tuple[float, float, list[float]]:
    vals = []
    for f in files:
        d = json.loads(Path(f).read_text())
        m = d["final_test_metrics"] if which == "test" else d["final_val_metrics"]
        vals.append(m[key])
    a = np.asarray(vals, dtype=np.float64)
    return float(a.mean()), float(a.std(ddof=0)), [float(v) for v in a]


def hist_stats(pattern: str, key: str) -> tuple[float, float]:
    vals = []
    for f in sorted(glob.glob(str(P4 / pattern))):
        d = json.loads(Path(f).read_text())
        vals.append(d["final_val_metrics"][key])
    a = np.asarray(vals, dtype=np.float64)
    return float(a.mean()), float(a.std(ddof=0))


def write(name: str, lines: list[str]) -> None:
    TABDIR.mkdir(exist_ok=True)
    (TABDIR / name).write_text("% AUTO-GENERATED by scripts/p10_render_paper_tables.py — do not edit\n"
                               + "\n".join(lines) + "\n")
    print(f"[p10] wrote tables/{name}")


def exploratory(p8: dict) -> None:
    cell = p8["cells"]["awc_n1200"]

    # ---- leakage table ----
    lk = p8["leakage"]
    L = [r"\begin{tabular}{lccc}", r"\toprule",
         r"historical cell & val steps & sharing a train episode & sharing a train goal \\",
         r"\midrule"]
    order = ["awc_n300", "awc_n500", "awc_n800", "awc_n1200", "awc_n2500", "awc_n5000", "ts_n1000"]
    names = {"awc_n300": r"all\_wc, $n{=}300$", "awc_n500": r"all\_wc, $n{=}500$",
             "awc_n800": r"all\_wc, $n{=}800$", "awc_n1200": r"all\_wc, $n{=}1200$",
             "awc_n2500": r"all\_wc, $n{=}2500$", "awc_n5000": r"all\_wc, $n{=}5000$",
             "ts_n1000": r"taps\_swipes, $n{=}1000$"}
    for k in order:
        v = lk[k]
        L.append(f"{names[k]} & {v['n_val']} & "
                 f"{v['val_steps_sharing_train_episode']} ({100*v['val_steps_sharing_train_episode_frac']:.0f}\\%) & "
                 f"{v['val_steps_sharing_train_goal']} ({100*v['val_steps_sharing_train_goal_frac']:.0f}\\%) \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("tab_leakage.tex", L)
    macro("LeakGoalMain", f"{100*lk['awc_n1200']['val_steps_sharing_train_goal_frac']:.0f}\\%")
    macro("LeakGoalMax", f"{100*lk['awc_n5000']['val_steps_sharing_train_goal_frac']:.0f}\\%")
    macro("LeakEpMain", f"{100*lk['awc_n1200']['val_steps_sharing_train_episode_frac']:.0f}\\%")

    # ---- exploratory main ablation ----
    pats = {
        "A (flat)": "variantA_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords.json",
        "B (aux loss)": "variantB_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords_aux1.0.json",
        "C (hard routing)": "variantC_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords.json",
        "D-hook (additive)": "Dhook_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords_init0.0.json",
        "D-token (prepended)": "Dtoken_seed4[234]_n1200_ep2_lr2e-05_mix-all_with_coords_init0.02.json",
    }
    ckey = {"B (aux loss)": "B_vs_A", "C (hard routing)": "C_vs_A",
            "D-hook (additive)": "Dhook_vs_A", "D-token (prepended)": "Dtoken_vs_A"}
    L = [r"\begin{tabular}{lcccc}", r"\toprule",
         r"variant & hit@0.10 & mean L2 $\downarrow$ & $\Delta$ hit@0.10 vs.\ A [95\% CI] & perm.\ $p$ \\",
         r"\midrule"]
    for nm, pat in pats.items():
        m10, s10 = hist_stats(pat, "hit_at_010")
        l2, _ = hist_stats(pat, "mean_normalized_l2")
        if nm in ckey:
            r = cell[ckey[nm]]["metrics"]["hit_at_010"]["episode_clustered"]
            L.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & {ci(r)} & {fmt_p(r)} \\\\")
        else:
            L.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & --- & --- \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("tab_exploratory_main.tex", L)

    rB = cell["B_vs_A"]["metrics"]["hit_at_010"]["episode_clustered"]
    macro("ExpBvsA", ci(rB))
    macro("ExpBvsAp", fmt_p(rB).strip("$"))
    macro("ExpBvsAHolm", f"{cell['B_vs_A']['metrics']['hit_at_010']['holm_adjusted_p_vsA_family']:.3f}")
    rD = cell["Dhook_vs_A"]["metrics"]["hit_at_010"]["episode_clustered"]
    macro("ExpDhvsA", ci(rD))
    macro("ExpDhvsAp", fmt_p(rD).strip("$"))
    macro("ExpDhvsAHolm", f"{cell['Dhook_vs_A']['metrics']['hit_at_010']['holm_adjusted_p_vsA_family']:.3f}")
    rDtB = cell["Dtoken_vs_B"]["metrics"]["hit_at_010"]["episode_clustered"]
    macro("ExpDtvsB", ci(rDtB))
    macro("ExpDtvsBp", fmt_p(rDtB).strip("$"))
    legacy = cell["B_vs_A"]["metrics"]["hit_at_010"]["legacy_pooled"]
    macro("ExpBvsApooled", f"{legacy['p_value']:.4g}")

    # ---- validation numbers ----
    v = p8["validation"]
    macro("TypeIPooled", f"{100*v['fixed_checkpoint_null']['pooled_reject_rate']:.1f}\\%")
    macro("TypeIClustered", f"{100*v['fixed_checkpoint_null']['clustered_reject_rate']:.1f}\\%")
    macro("TypeISims", str(v["fixed_checkpoint_null"]["n_sims"]))
    macro("TypeIProc", f"{100*v['procedure_null_with_run_offsets']['clustered_reject_rate']:.0f}\\%")

    # ---- exploratory causal table ----
    if "dtoken_causal_n1200" in p8["cells"]:
        cc = p8["cells"]["dtoken_causal_n1200"]
        L = [r"\begin{tabular}{lccc}", r"\toprule",
             r"contrast & $\Delta$ hit@0.10 [95\% CI] & $\Delta$ hit@0.25 [95\% CI] & perm.\ $p$ (hit@0.10) \\",
             r"\midrule"]
        for key, label in [("wrong_vs_gold", "wrong $-$ gold"), ("zero_vs_gold", "zero $-$ gold")]:
            r10 = cc[key]["metrics"]["hit_at_010"]["episode_clustered"]
            r25 = cc[key]["metrics"]["hit_at_025"]["episode_clustered"]
            L.append(f"{label} & {ci(r10)} & {ci(r25)} & {fmt_p(r10)} \\\\")
        L += [r"\bottomrule", r"\end{tabular}"]
        write("tab_causal.tex", L)

    # ---- exploratory e2e ----
    if "e2e_n1200" in p8["cells"]:
        ee = p8["cells"]["e2e_n1200"]
        rp = ee["predicted_vs_flatA"]["metrics"]["hit_at_010"]["episode_clustered"]
        ro = ee["oracle_vs_flatA"]["metrics"]["hit_at_010"]["episode_clustered"]
        rg = ee["predicted_vs_oracle"]["metrics"]["hit_at_010"]["episode_clustered"]
        macro("ExpEtoEPredvsA", ci(rp)); macro("ExpEtoEPredvsAp", fmt_p(rp).strip("$"))
        macro("ExpEtoEOraclevsA", ci(ro))
        macro("ExpEtoEGap", ci(rg))


def confirmatory(p9: dict) -> None:
    fs = "_fs-aitw_frozen_v1"

    # ---- descriptive test means ----
    pats = {
        "A (flat)": f"variantA_seed4[234]_n1200_*mix-all_with_coords{fs}.json",
        "B (aux loss)": f"variantB_seed4[234]_n1200_*aux1.0{fs}.json",
        "C (hard routing)": f"variantC_seed4[234]_n1200_*mix-all_with_coords{fs}.json",
        "D-hook (additive)": f"Dhook_seed4[234]_n1200_*init0.0{fs}.json",
        "D-token (prepended)": f"Dtoken_seed4[234]_n1200_*init0.02_causal{fs}.json",
    }
    stats = {}
    for nm, pat in pats.items():
        files = sorted(glob.glob(str(P4 / pat)))
        if len(files) != 3:
            print(f"[p10] WARNING: {nm}: {len(files)} test runs found (expected 3)")
        if files:
            stats[nm] = {
                "hit010": seed_stats(files, "test", "hit_at_010"),
                "hit025": seed_stats(files, "test", "hit_at_025"),
                "l2": seed_stats(files, "test", "mean_normalized_l2"),
                "parse": seed_stats(files, "test", "parse_rate"),
            }
    pri = p9["primary"]
    cmap = {"B (aux loss)": ("P1_B_vs_A", False), "D-hook (additive)": ("P2_Dhook_vs_A", False),
            "C (hard routing)": ("C_vs_A", True), "D-token (prepended)": ("Dtoken_vs_A", True)}
    L = [r"\begin{tabular}{lcccc}", r"\toprule",
         r"variant & hit@0.10 & mean L2 $\downarrow$ & $\Delta$ hit@0.10 vs.\ A [95\% CI] & perm.\ $p$ (Holm) \\",
         r"\midrule"]
    for nm in pats:
        if nm not in stats:
            continue
        m10, s10, _ = stats[nm]["hit010"]
        l2, _, _ = stats[nm]["l2"]
        if nm in cmap:
            key, secondary = cmap[nm]
            src = p9["secondary"] if secondary else p9["primary"]
            r = src[key]["metrics"]["hit_at_010"]["episode_clustered"]
            holm = "" if secondary else f" ({src[key]['holm_adjusted_p_hit010']:.3g})"
            L.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & {ci(r)} & {fmt_p(r)}{holm} \\\\")
        else:
            L.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & --- & --- \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("tab_confirmatory_main.tex", L)

    for mk, key in [("ConfBvsA", "P1_B_vs_A"), ("ConfDhvsA", "P2_Dhook_vs_A"),
                    ("ConfDtvsB", "P3_Dtoken_vs_B"), ("ConfEtoEvsA", "P4_e2e_pred_vs_A")]:
        r = pri[key]["metrics"]["hit_at_010"]["episode_clustered"]
        macro(mk, ci(r))
        macro(mk + "p", fmt_p(r).strip("$"))
        macro(mk + "Holm", f"{pri[key]['holm_adjusted_p_hit010']:.3g}")
        rl = pri[key]["metrics"]["mean_normalized_l2"]["episode_clustered"]
        macro(mk + "Ltwo", ci(rl))
        macro(mk + "Ltwop", fmt_p(rl).strip("$"))

    if "A (flat)" in stats:
        m10, s10, seeds = stats["A (flat)"]["hit010"]
        macro("ConfAhit", f"{m10:.3f} \\pm {s10:.3f}")
        pr, _, _ = stats["A (flat)"]["parse"]
        macro("ConfAparse", f"{100*pr:.1f}\\%")
    if "B (aux loss)" in stats:
        m10, s10, _ = stats["B (aux loss)"]["hit010"]
        macro("ConfBhit", f"{m10:.3f} \\pm {s10:.3f}")

    # ---- control ----
    rows = []
    for nm, pat, key in [
        ("A (flat)", f"variantA_seed4[234]_n1000_*mix-taps_and_swipes{fs}.json", None),
        ("B (aux loss)", f"variantB_seed4[234]_n1000_*taps_and_swipes_aux1.0{fs}.json", "control_B_vs_A"),
        ("C (hard routing)", f"variantC_seed4[234]_n1000_*mix-taps_and_swipes{fs}.json", "control_C_vs_A"),
        ("D-hook (additive)", f"Dhook_seed4[234]_n1000_*taps_and_swipes_init0.0{fs}.json", "control_Dhook_vs_A"),
    ]:
        files = sorted(glob.glob(str(P4 / pat)))
        if not files:
            continue
        m10, s10, _ = seed_stats(files, "test", "hit_at_010")
        l2, _, _ = seed_stats(files, "test", "mean_normalized_l2")
        if key and key in p9["secondary"]:
            r = p9["secondary"][key]["metrics"]["hit_at_010"]["episode_clustered"]
            rows.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & {ci(r)} & {fmt_p(r)} \\\\")
        else:
            rows.append(f"{nm} & ${m10:.3f} \\pm {s10:.3f}$ & ${l2:.3f}$ & --- & --- \\\\")
    if rows:
        L = [r"\begin{tabular}{lcccc}", r"\toprule",
             r"variant & hit@0.10 & mean L2 $\downarrow$ & $\Delta$ hit@0.10 vs.\ A [95\% CI] & perm.\ $p$ \\",
             r"\midrule"] + rows + [r"\bottomrule", r"\end{tabular}"]
        write("tab_control.tex", L)

    # ---- low-data grid ----
    rows = []
    for n in (300, 500, 800):
        cols = [f"$n{{=}}{n}$"]
        fa = sorted(glob.glob(str(P4 / f"variantA_seed4[234]_n{n}_*mix-all_with_coords{fs}.json")))
        if not fa:
            continue
        ma, _, _ = seed_stats(fa, "test", "hit_at_010")
        cols.append(f"${ma:.3f}$")
        for vk, ck in [("variantB", f"lowdata{n}_B_vs_A"), ("Dhook", f"lowdata{n}_Dhook_vs_A")]:
            if ck in p9["secondary"]:
                r = p9["secondary"][ck]["metrics"]["hit_at_010"]["episode_clustered"]
                cols.append(ci(r))
            else:
                cols.append("---")
        rows.append(" & ".join(cols) + r" \\")
    if rows:
        L = [r"\begin{tabular}{lccc}", r"\toprule",
             r"train size & A hit@0.10 & $\Delta$ B$-$A [95\% CI] & $\Delta$ D-hook$-$A [95\% CI] \\",
             r"\midrule"] + rows + [r"\bottomrule", r"\end{tabular}"]
        write("tab_lowdata.tex", L)

    # ---- e2e on test ----
    e2f = sorted(glob.glob(str(P4 / f"e2e_seed4[234]_n1200_*mix-all_with_coords{fs}.json")))
    if e2f:
        po, pp, s1a = [], [], []
        for f in e2f:
            d = json.loads(Path(f).read_text())
            tb = d["final_test_metrics"]
            po.append(tb["oracle_metrics"]["hit_at_010"])
            pp.append(tb["predicted_metrics"]["hit_at_010"])
            s1a.append(tb["stage1_test_acc"])
        macro("ConfEtoEOracle", f"{np.mean(po):.3f} \\pm {np.std(po):.3f}")
        macro("ConfEtoEPred", f"{np.mean(pp):.3f} \\pm {np.std(pp):.3f}")
        macro("ConfStageOneAcc", f"{np.mean(s1a):.3f}")
        rg = p9["secondary"]["e2e_pred_vs_oracle"]["metrics"]["hit_at_010"]["episode_clustered"]
        macro("ConfEtoEGap", ci(rg))


def main() -> None:
    TABDIR.mkdir(exist_ok=True)
    p8 = json.loads(P8.read_text())
    exploratory(p8)
    if P9.exists():
        confirmatory(json.loads(P9.read_text()))
    else:
        print("[p10] rerun_analysis.json missing — confirmatory tables NOT rendered")
        for t in ("tab_confirmatory_main.tex", "tab_control.tex", "tab_lowdata.tex"):
            write(t, [r"\begin{tabular}{l}\textbf{PENDING: confirmatory rerun results not yet rendered}\end{tabular}"])
    lines = [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in MACROS.items()]
    write("macros.tex", lines)
    print(f"[p10] {len(MACROS)} macros")


if __name__ == "__main__":
    main()
